-- ============================================================================
-- V6_0_0 : Tables applicatives absentes du schema production HPS
--
-- ALERT_EVENT, SLA_SNAPSHOT et SOCKET_LOGS sont des tables propres a
-- l'application (pas issues du schema banking officiel AUTHO_ACTIVITY_ADM).
-- Elles correspondent aux entites JPA AlertEventEntity, SlaSnapshotEntity et
-- SocketLogEntity (GenerationType.IDENTITY -> colonnes IDENTITY Oracle 12c+).
-- ============================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = PFE_SW_MON;
SET SQLBLANKLINES ON

-- ============================================================================
-- ALERT_EVENT (AlertEventEntity)
-- ============================================================================
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE ALERT_EVENT (
            ID           NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            RULE_ID      NUMBER,
            TX_ID        NUMBER,
            TYPE         VARCHAR2(50)   NOT NULL,
            SEVERITY     VARCHAR2(20)   NOT NULL,
            TITLE        VARCHAR2(180)  NOT NULL,
            DETAILS      VARCHAR2(1000),
            STATUS       VARCHAR2(20)   NOT NULL,
            CREATED_AT   TIMESTAMP      NOT NULL,
            ACK_BY       NUMBER,
            ACK_AT       TIMESTAMP,
            RESOLVED_BY  NUMBER,
            RESOLVED_AT  TIMESTAMP,
            CONSTRAINT PK_ALERT_EVENT PRIMARY KEY (ID)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- SLA_SNAPSHOT (SlaSnapshotEntity)
-- ============================================================================
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE SLA_SNAPSHOT (
            ID                 NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            SLA_DEFINITION_ID  NUMBER         NOT NULL,
            PERIOD_START       TIMESTAMP      NOT NULL,
            PERIOD_END         TIMESTAMP      NOT NULL,
            SUCCESS_RATE       NUMBER(6,2),
            AVG_LATENCY_MS     NUMBER,
            P95_LATENCY_MS     NUMBER,
            UPTIME_RATE        NUMBER(6,2),
            BREACHED           NUMBER(1)      NOT NULL,
            CALCULATED_AT      TIMESTAMP      NOT NULL,
            CONSTRAINT PK_SLA_SNAPSHOT PRIMARY KEY (ID)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- SOCKET_LOGS (SocketLogEntity)
-- ============================================================================
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE SOCKET_LOGS (
            ID                        NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            TRANSACTION_ID            NUMBER         NOT NULL,
            LOG_TIMESTAMP             TIMESTAMP      NOT NULL,
            CHANNEL                   VARCHAR2(20)   NOT NULL,
            DIRECTION                 VARCHAR2(10)   NOT NULL,
            MESSAGE_TYPE              VARCHAR2(50),
            SOCKET_HOST               VARCHAR2(100),
            SOCKET_PORT               NUMBER,
            MESSAGE_LENGTH            NUMBER,
            RESPONSE_TIME_MS          NUMBER,
            SOCKET_CONNECT_TIME_MS    NUMBER,
            SOCKET_TRANSFER_TIME_MS   NUMBER,
            STATUS                    VARCHAR2(20)   NOT NULL,
            ERROR_CODE                VARCHAR2(10),
            ERROR_MESSAGE             VARCHAR2(4000),
            HEX_DUMP                  CLOB,
            RETRY_COUNT               NUMBER,
            CREATED_AT                TIMESTAMP      NOT NULL,
            CONSTRAINT PK_SOCKET_LOGS PRIMARY KEY (ID)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
